export const QUEUE = {
    NAME: "video-download",
    JOB_NAME: "download",
    MAX_ATTEMPTS: 3,
    RETRY_DELAY_MS: 3000,
    WORKER_CONCURRENCY: 3,
    RATE_LIMITER_MAX: 5,
    RATE_LIMITER_DURATION_MS: 1000,
    KEEP_COMPLETED: 50,
    KEEP_FAILED: 25,
    STALLED_INTERVAL_MS: 30_000,
    LOCK_DURATION_MS: 120_000,
} as const;
